using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;

namespace OCShell {
  public sealed class VoiceSettings {
    readonly CompanionAudio audio;readonly QwenVoice voice;readonly InteractionVoices scripts;readonly string root,role;readonly RoleVisual style;
    readonly Dictionary<string,TextBox> ids=new Dictionary<string,TextBox>(),refs=new Dictionary<string,TextBox>(),urls=new Dictionary<string,TextBox>(),roleModels=new Dictionary<string,TextBox>();readonly Dictionary<string,TextBlock> states=new Dictionary<string,TextBlock>();
    readonly Dictionary<string,string> displayedIds=new Dictionary<string,string>(),displayedModels=new Dictionary<string,string>();bool displayedReactions,displayedChat;
    readonly PasswordBox key=new PasswordBox();readonly TextBox workspace=new TextBox(),model=new TextBox(),endpoint=new TextBox();readonly ComboBox provider=new ComboBox();
    readonly CheckBox sfx=new CheckBox(),reactions=new CheckBox(),chat=new CheckBox(),cloudSpeech=new CheckBox();readonly Slider volume=new Slider{Minimum=0,Maximum=1};
    readonly TextBlock status=new TextBlock{TextWrapping=TextWrapping.Wrap,FontSize=12};readonly TabControl tabs=new TabControl();readonly ListBox lines=new ListBox();readonly ComboBox selected=new ComboBox();
    readonly Button save,all,bake,stop;CancellationTokenSource task;bool busy;TouchLine current;
    public readonly Window Window;
    Brush Paint(string color){return RoleVisual.Paint(color);}
    TextBlock Text(string s,double size=12){return new TextBlock{Text=s,FontSize=size,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,0,0,8)};}
    TextBox Input(string value){return new TextBox{Text=value??"",Padding=new Thickness(10,7,10,7),BorderThickness=new Thickness(1),BorderBrush=Paint(style.Line),Background=Paint(style.Paper),Foreground=Paint(style.Ink),Margin=new Thickness(0,0,0,9)};}
    void Field(Panel panel,string label,Control input){panel.Children.Add(Text(label));input.Padding=new Thickness(10,7,10,7);input.Margin=new Thickness(0,0,0,10);input.BorderBrush=Paint(style.Line);input.Background=Paint(style.Paper);input.Foreground=Paint(style.Ink);panel.Children.Add(input);}
    Button Button(string label,Action click){var button=new Button{Content=label,Padding=new Thickness(12,9,12,9),Margin=new Thickness(0,0,8,8),Background=Paint(style.Paper),Foreground=Paint(style.Ink),BorderBrush=Paint(style.Line),Cursor=System.Windows.Input.Cursors.Hand};var template=new ControlTemplate(typeof(Button));var surface=new FrameworkElementFactory(typeof(Border));surface.SetValue(Border.CornerRadiusProperty,new CornerRadius(15));surface.SetValue(Border.BackgroundProperty,new TemplateBindingExtension(Control.BackgroundProperty));surface.SetValue(Border.BorderBrushProperty,new TemplateBindingExtension(Control.BorderBrushProperty));surface.SetValue(Border.BorderThicknessProperty,new Thickness(1));surface.SetValue(Border.PaddingProperty,new TemplateBindingExtension(Control.PaddingProperty));var content=new FrameworkElementFactory(typeof(ContentPresenter));content.SetValue(ContentPresenter.HorizontalAlignmentProperty,HorizontalAlignment.Center);surface.AppendChild(content);template.VisualTree=surface;var hover=new Trigger{Property=UIElement.IsMouseOverProperty,Value=true};hover.Setters.Add(new Setter(UIElement.OpacityProperty,.8));template.Triggers.Add(hover);button.Template=template;if(click!=null)button.Click+=delegate{click();};return button;}
    Border Card(UIElement child){return new Border{Child=child,CornerRadius=new CornerRadius(20),Padding=new Thickness(16),Margin=new Thickness(0,0,0,14),Background=Paint(style.Paper),BorderBrush=Paint(style.Line),BorderThickness=new Thickness(1)};}
    void Notify(string message){if(Window.Dispatcher.CheckAccess())status.Text=message;else Window.Dispatcher.BeginInvoke(new Action(delegate{status.Text=message;}));}
    public VoiceSettings(CompanionAudio audio,string root,string role,FontFamily font,Window owner){
      this.audio=audio;voice=audio.Voice;this.root=root;this.role=role;style=RoleVisual.For(role);scripts=audio.Interactions;
      Window=new Window{Title="角色声音工作台 · "+role.ToUpperInvariant(),Width=680,Height=820,MinWidth=590,MinHeight=640,Background=Paint(style.Paper),Foreground=Paint(style.Ink),FontFamily=font,FontSize=13,WindowStartupLocation=owner==null?WindowStartupLocation.CenterScreen:WindowStartupLocation.CenterOwner,ShowInTaskbar=owner==null};if(owner!=null)Window.Owner=owner;
      Window.MaxHeight=Math.Max(640,SystemParameters.WorkArea.Height);var layout=new DockPanel{Margin=new Thickness(22),Background=Paint(style.Paper)};Window.Content=layout;
      var heading=new StackPanel();heading.Children.Add(Text("声音小作坊  ♫",24));heading.Children.Add(Text("内置互动台词离线播放 · 可选Qwen音色克隆与新语音合成",13));DockPanel.SetDock(heading,Dock.Top);layout.Children.Add(heading);
      var footer=new StackPanel{Margin=new Thickness(0,14,0,0)};status.Text="内置互动台词无需Key即可播放。联网合成可在此便携版独立配置；密钥与绑定只保存到本机。";footer.Children.Add(status);var actions=new WrapPanel{Margin=new Thickness(0,10,0,0)};
      save=Button("保存设置",delegate{Persist();});all=Button("克隆并烘焙这一位",delegate{Run(async delegate(CancellationToken token){string character=SelectedRole();if(!voice.Options.EnableCloudSpeech){Notify("若要制作新声音，请先勾选启用联网合成；内置互动台词可直接离线试听。");return;}if(!await CloneOne(character,token))return;await VoiceBakeJob.BakeRoles(voice,scripts,new[]{character},token,Notify);voice.Options.Chat=true;voice.Save(voice.Options,"");Refresh();Notify("本角色音色已绑定，日语触碰语音已存到本机。聊天朗读与触碰语音已启用。 ");});});stop=Button("停止",delegate{if(task!=null)task.Cancel();audio.StopVoice();Notify("已停止；生成成功的音色、语音与进度保留。 ");});actions.Children.Add(save);actions.Children.Add(all);actions.Children.Add(stop);footer.Children.Add(actions);DockPanel.SetDock(footer,Dock.Bottom);layout.Children.Add(footer);
      tabs.Background=Paint(style.Paper);tabs.BorderBrush=Paint(style.Line);layout.Children.Add(tabs);
      var setup=new StackPanel{Margin=new Thickness(12)};var account=new StackPanel();account.Children.Add(Text("北京百炼 · Qwen Audio 3.1",17));account.Children.Add(Text("每位角色可以分别使用 Flash 或 Realtime Plus；到“角色音色”查看与修改。相同文本、音色与语气会复用本地缓存。"));
      provider.ItemsSource=new[]{"北京百炼 · 3.1 推荐","新加坡百炼 · 旧接口","本地 WAV 兼容服务"};provider.SelectedIndex=voice.Options.Provider=="local"?2:voice.Options.Provider=="singapore"?1:0;Field(account,"服务地域",provider);
      workspace.Text=voice.Options.WorkspaceId;Field(account,"业务空间 ID（可选；留空使用北京兼容网关）",workspace);key.ToolTip="留空保留本机已加密的 Key；不会显示现有密钥";Field(account,"API Key · 留空保留现有值",key);
      var links=new WrapPanel();links.Children.Add(Button("打开百炼控制台 ↗",delegate{Process.Start(new ProcessStartInfo("https://bailian.console.aliyun.com/"){UseShellExecute=true});}));account.Children.Add(links);
      model.Text=voice.Options.Model;Field(account,"默认模型 · 单独指定的角色沿用自己的模型",model);var advanced=new StackPanel();endpoint.Text=voice.Options.Endpoint;Field(advanced,"本地接口地址（仅本地模式使用）",endpoint);account.Children.Add(new Expander{Header="本地服务设置",Content=advanced,Margin=new Thickness(0,0,0,8)});setup.Children.Add(Card(account));
      var playback=new StackPanel();playback.Children.Add(Text("播放偏好",17));sfx.Content="互动捏捏音效";sfx.IsChecked=voice.Options.Sfx;reactions.Content="日语触碰反应（气泡显示中文释义）";reactions.IsChecked=voice.Options.Reactions;chat.Content="实时朗读聊天回复（跟随回复语种）";chat.IsChecked=voice.Options.Chat;cloudSpeech.Content="启用联网合成（需此便携版独立Key与音色；内置语音无需联网）";cloudSpeech.IsChecked=voice.Options.EnableCloudSpeech;foreach(var box in new[]{sfx,reactions,chat,cloudSpeech}){box.Margin=new Thickness(0,0,0,10);playback.Children.Add(box);}volume.Value=voice.Options.Volume;Field(playback,"音量",volume);setup.Children.Add(Card(playback));AddTab("连接与播放",setup);
      var characters=new StackPanel{Margin=new Thickness(12)};characters.Children.Add(Text("参考音只在点击“上传复刻”时发送到百炼。自动上传使用百炼临时存储；也可展开填写自己托管的 HTTPS 音频链接。建议清晰日常说话，10–20 秒，16 bit WAV。"));
      foreach(string character in QwenVoice.Roles){
        string c=character;var card=new StackPanel();var banner=new StackPanel{Orientation=Orientation.Horizontal};string avatar=Path.Combine(root,"assets",c+"-tab-avatar.png");if(File.Exists(avatar))banner.Children.Add(new Image{Source=new BitmapImage(new Uri(avatar)),Width=40,Height=40,Margin=new Thickness(0,0,10,12)});
        banner.Children.Add(Text(QwenVoice.RoleName(c),15));card.Children.Add(banner);string customModel;voice.Options.Models.TryGetValue(c,out customModel);roleModels[c]=Input(customModel??"");Field(card,"本角色模型 · 留空沿用默认；换模型后需重新复刻音色",roleModels[c]);
        refs[c]=Input(voice.Options.References[c]);Field(card,"日语参考音（本地 WAV）",refs[c]);var commands=new WrapPanel();commands.Children.Add(Button("选择音频…",delegate{var picker=new Microsoft.Win32.OpenFileDialog{Filter="16 bit PCM WAV|*.wav",CheckFileExists=true,Title="选择 "+c+" 的声音参考"};if(picker.ShowDialog(Window)==true){try{WaveInfo.Read(File.ReadAllBytes(picker.FileName),true);refs[c].Text=picker.FileName;Notify("已选择参考音，尚未上传。");}catch(Exception e){Notify(e.Message);}}}));commands.Children.Add(Button("试听参考音",delegate{if(File.Exists(refs[c].Text))audio.PlayFile(refs[c].Text);else Notify("参考音路径不存在。");}));commands.Children.Add(Button("上传复刻",delegate{Run(async delegate(CancellationToken token){await CloneOne(c,token);});}));commands.Children.Add(Button("查询音色",delegate{Run(async delegate(CancellationToken token){await voice.Query(c,token);Refresh();Notify(c+" 音色状态已更新。");});}));card.Children.Add(commands);
        ids[c]=Input(voice.Options.Voices[c]);Field(card,"绑定的音色 ID（也可填已创建音色）",ids[c]);var hosted=new StackPanel();urls[c]=Input(voice.Options.ReferenceUrls[c]);Field(hosted,"可选：无需鉴权的 HTTPS 音频链接（内容应与所选本地参考音相同）",urls[c]);card.Children.Add(new Expander{Header="已有托管音源",Content=hosted});states[c]=Text("");card.Children.Add(states[c]);characters.Children.Add(Card(card));
      }AddTab("角色音色",characters);
      var script=new DockPanel{Margin=new Thickness(12)};var top=new StackPanel();var roleChoices=new List<string>();foreach(string itemRole in QwenVoice.Roles)roleChoices.Add(QwenVoice.RoleName(itemRole)+" · "+scripts.Lines(itemRole).Count+" 条");selected.ItemsSource=roleChoices;selected.SelectedIndex=Math.Max(0,Array.IndexOf(QwenVoice.Roles,role));Field(top,"日语原声 + 中文释义",selected);var row=new WrapPanel();row.Children.Add(Button("试听选中台词",delegate{Run(async delegate(CancellationToken token){if(current==null)return;string file=scripts.Cached(voice,SelectedRole(),current);if(file==null){if(!voice.CanSynthesize(SelectedRole())){Notify("这句没有本地语音；请先配置并启用联网合成。");return;}file=await voice.Bake(SelectedRole(),current.Japanese,token,scripts.Direction(current),"ja");}audio.PlayFile(file);Notify("正在试听 "+current.Id);});}));bake=Button("烘焙这一位",delegate{Run(async delegate(CancellationToken token){if(!voice.CanSynthesize(SelectedRole())){Notify("请先配置并启用联网合成；内置语音已可离线播放。");return;}await scripts.Bake(voice,new[]{SelectedRole()},token,Notify);Refresh();});});row.Children.Add(bake);row.Children.Add(Button("打开本地语音文件夹 ↗",delegate{Directory.CreateDirectory(scripts.ExportFolder);Process.Start(new ProcessStartInfo(scripts.ExportFolder){UseShellExecute=true});}));top.Children.Add(row);DockPanel.SetDock(top,Dock.Top);script.Children.Add(top);lines.Background=Paint(style.Paper);lines.BorderBrush=Paint(style.Line);lines.HorizontalContentAlignment=HorizontalAlignment.Stretch;script.Children.Add(lines);lines.SelectionChanged+=delegate{var item=lines.SelectedItem as ListBoxItem;current=item==null?null:item.Tag as TouchLine;};selected.SelectionChanged+=delegate{LoadLines();};tabs.Items.Add(new TabItem{Header="日语触碰台词",Content=script});LoadLines();Refresh();
      Window.Closed+=delegate{if(task!=null)task.Cancel();audio.StopVoice();};
    }
    void AddTab(string name,UIElement element){tabs.Items.Add(new TabItem{Header=name,Content=new ScrollViewer{Content=element,VerticalScrollBarVisibility=ScrollBarVisibility.Auto}});}
    string SelectedRole(){return QwenVoice.Roles[Math.Max(0,selected.SelectedIndex)];}
    void LoadLines(){lines.Items.Clear();foreach(var line in scripts.Lines(SelectedRole())){var item=new StackPanel{Margin=new Thickness(8)};item.Children.Add(Text(line.Japanese,15));item.Children.Add(Text(line.Chinese,12));item.Children.Add(new TextBlock{Text=line.Context+" · "+line.Id,FontSize=10,Opacity=.65});lines.Items.Add(new ListBoxItem{Content=item,Tag=line});}if(lines.Items.Count>0)lines.SelectedIndex=0;}
    void Refresh(){foreach(string c in QwenVoice.Roles){ids[c].Text=voice.Options.Voices[c];displayedIds[c]=ids[c].Text;string customModel;voice.Options.Models.TryGetValue(c,out customModel);roleModels[c].Text=customModel??"";displayedModels[c]=roleModels[c].Text;CloneRecord record;string state=voice.Options.Clones.TryGetValue(c,out record)?record.Status:voice.Options.Voices[c].Length>0?"手动绑定":"等待上传";string reference="";try{reference=" · "+WaveInfo.Read(File.ReadAllBytes(voice.Options.References[c]),true).Seconds.ToString("0.0")+" 秒参考音";}catch{}states[c].Text=QwenVoice.Model(voice.Options,c)+" · "+state+reference+" · "+scripts.ReadyCount(voice,c)+" / "+scripts.Lines(c).Count+" 条本地语音";}displayedReactions=voice.Options.Reactions;displayedChat=voice.Options.Chat;reactions.IsChecked=displayedReactions;chat.IsChecked=displayedChat;}
    bool Persist(){try{voice.ReloadIfChanged();var o=voice.Options;o.Provider=provider.SelectedIndex==2?"local":provider.SelectedIndex==1?"singapore":"beijing";o.WorkspaceId=workspace.Text.Trim();o.Model=model.Text.Trim();if(o.Model.Length==0)throw new InvalidDataException("请填写语音模型名称");o.Endpoint=endpoint.Text.Trim();o.Sfx=sfx.IsChecked==true;if((reactions.IsChecked==true)!=displayedReactions)o.Reactions=reactions.IsChecked==true;if((chat.IsChecked==true)!=displayedChat)o.Chat=chat.IsChecked==true;o.Volume=volume.Value;o.EnableCloudSpeech=cloudSpeech.IsChecked==true;foreach(string c in QwenVoice.Roles){if(roleModels[c].Text.Trim()!=displayedModels[c]){if(roleModels[c].Text.Trim().Length==0)o.Models.Remove(c);else o.Models[c]=roleModels[c].Text.Trim();}if(ids[c].Text.Trim()!=displayedIds[c])o.Voices[c]=ids[c].Text.Trim();o.References[c]=refs[c].Text.Trim();o.ReferenceUrls[c]=urls[c].Text.Trim();}voice.Save(o,key.Password);key.Clear();Notify("设置已保存。本机 Key 使用当前 Windows 用户加密。");return true;}catch(Exception e){Notify(e is InvalidDataException?e.Message:"声音设置未能保存");return false;}}
    async Task<bool> CloneOne(string c,CancellationToken token){var record=await voice.Clone(c,token,Notify);if(record.Status!="OK"&&!await voice.WaitClone(c,token,Notify)){Notify(c+" 音色仍在准备；ID 已保存，可稍后点击“查询音色”，无需再次上传。");Refresh();return false;}Refresh();Notify(c+" 音色已绑定。可试听台词或继续烘焙。");return true;}
    async void Run(Func<CancellationToken,Task> work){if(busy||!Persist())return;busy=true;task=new CancellationTokenSource();tabs.IsEnabled=save.IsEnabled=all.IsEnabled=false;try{await work(task.Token);}catch(OperationCanceledException){Notify("已停止。成功生成的文件和音色保留。");}catch(Exception e){Notify(e is InvalidOperationException||e is InvalidDataException?e.Message:"语音流程未完成；已生成的内容保留，可继续重试。");}finally{busy=false;tabs.IsEnabled=save.IsEnabled=all.IsEnabled=true;task.Dispose();task=null;}}
  }
}
